package org.example.gui.schema.add;

import org.example.gui.ChangeableGui;;
import org.example.gui.pdf_viewer.PdfViewerGui;
import org.springframework.stereotype.Component;

import javax.swing.*;
import java.awt.*;
import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.util.Optional;

@Component
public class AddSchemaGui extends ChangeableGui {

    private JPanel mainPanel;
    private JPanel pdfViewerPanel;
    private JPanel managementPanel;
    private JButton prevPageButton;
    private JButton nextPageButton;

    private final PdfViewerGui pdfViewerGui;
    private final AddSchemaManagementGui addSchemaManagementGui;

    public AddSchemaGui(AddSchemaManagementGui addSchemaManagementGui) {

        this.pdfViewerGui = new PdfViewerGui(addSchemaManagementGui::handleOnSelect);
        this.addSchemaManagementGui = addSchemaManagementGui;

        $$$setupUI$$$();

        prevPageButton.addActionListener(l -> pdfViewerGui.changeToPrevPage());
        nextPageButton.addActionListener(l -> pdfViewerGui.changeToNextPage());
    }

    public void handleSelectPdf() {

        Optional<File> gotFileOpt = pdfViewerGui.handleSelectPdfFile();

        if (gotFileOpt.isEmpty()) {
            return;
        }

        File gotFile = gotFileOpt.get();

        byte[] fileData = null;

        try {
            fileData = Files.readAllBytes(gotFile.toPath());

            addSchemaManagementGui.setFileData(fileData);
        } catch (IOException e) {

            e.printStackTrace();
        }
    }

    @Override
    public JPanel getMainPanel() {

        return mainPanel;
    }

    private void createUIComponents() {
        // TODO: place custom component creation code here

        pdfViewerPanel = pdfViewerGui.getMainPanel();
        managementPanel = addSchemaManagementGui.getMainPanel();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        createUIComponents();
        mainPanel = new JPanel();
        mainPanel.setLayout(new GridBagLayout());
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.gridwidth = 3;
        gbc.weightx = 8.0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.BOTH;
        mainPanel.add(pdfViewerPanel, gbc);
        gbc = new GridBagConstraints();
        gbc.gridx = 3;
        gbc.gridy = 0;
        gbc.gridheight = 2;
        gbc.weightx = 3.0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.BOTH;
        mainPanel.add(managementPanel, gbc);
        nextPageButton = new JButton();
        nextPageButton.setText(">");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 1;
        gbc.weightx = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.insets = new Insets(20, 10, 20, 0);
        mainPanel.add(nextPageButton, gbc);
        prevPageButton = new JButton();
        prevPageButton.setText("<");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 1;
        gbc.weightx = 1.0;
        gbc.anchor = GridBagConstraints.EAST;
        gbc.insets = new Insets(20, 0, 20, 10);
        mainPanel.add(prevPageButton, gbc);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return mainPanel;
    }

}
