package org.example.gui;

import javax.swing.*;
import java.awt.*;

public class Window {

    private JPanel mainPanel;

    private GridBagConstraints mainPanelLayoutConstrains;

    public Window() {

        loadMainPanelLayoutConstraints();

        JFrame frame = new JFrame("Faktury");

        frame.setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        frame.setSize(1274, 1000);
        frame.setLocationRelativeTo(null);

        PdfViewerGui pdfViewerGui = new PdfViewerGui();

        frame.add(mainPanel);

        changeMainPanelContent(pdfViewerGui.getMainPanel());

        frame.setVisible(true);
    }

    private void loadMainPanelLayoutConstraints() {

        mainPanelLayoutConstrains = new GridBagConstraints();

        mainPanelLayoutConstrains.gridx = 0;
        mainPanelLayoutConstrains.gridy = 0;
        mainPanelLayoutConstrains.fill = GridBagConstraints.BOTH;
        mainPanelLayoutConstrains.weightx = 1;
        mainPanelLayoutConstrains.weighty = 1;
    }

    private void changeMainPanelContent(Component component) {

        mainPanel.removeAll();
        mainPanel.add(component, mainPanelLayoutConstrains);

        mainPanel.revalidate();
        mainPanel.repaint();
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        mainPanel = new JPanel();
        mainPanel.setLayout(new GridBagLayout());
        mainPanel.setMinimumSize(new Dimension(0, 0));
        mainPanel.setPreferredSize(new Dimension(0, 0));
        mainPanel.setRequestFocusEnabled(true);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return mainPanel;
    }

}
