package org.example.gui;

import org.example.gui.integration.InvoicesGui;
import org.example.gui.integration.LoginGui;
import org.example.gui.manage_pdf.PdfViewerGui;
import org.example.service.auth.AuthService;

import javax.swing.*;
import java.awt.*;

@org.springframework.stereotype.Component
public class Window {

    private final JFrame frame;

    private JPanel mainPanel;

    private GridBagConstraints mainPanelLayoutConstrains;

    private final LoginGui loginGui;
    private final InvoicesGui invoicesGui;

    private final AuthService authService;

    public Window(LoginGui loginGui, InvoicesGui invoicesGui, AuthService authService) {

        this.loginGui = loginGui;
        this.invoicesGui = invoicesGui;

        invoicesGui.setHandleLogout(this::handleLogout);

        this.authService = authService;

        loadMainPanelLayoutConstraints();

        frame = new JFrame("Integracja faktur zakupu z Gmaila i Subiekt GT");

        frame.setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        frame.setSize(1000, 800);
        frame.setLocationRelativeTo(null);

        loginGui.setHandleSuccessAuth(this::handleSuccessAuth);

        handleAuth();

        frame.add(mainPanel);

        frame.setVisible(true);
    }

    private void handleAuth() {

        if (authService.doesUserPassedFirstLoginToApp() && authService.isUserLogged()) {

            handleSuccessAuth();
        }
        else {

            changeMainPanelContent(loginGui);
        }
    }

    public void handleSuccessAuth() {

        loadMenu();

        invoicesGui.load();

        changeMainPanelContent(invoicesGui);
    }

    private void loadMenu() {

        JMenuBar menuBar = new JMenuBar();

        JMenu accountMenu = new JMenu("Konto");

        JMenuItem accountMenuItem = new JMenuItem("Wyloguj");
        accountMenuItem.addActionListener(e -> handleLogout());

        accountMenu.add(accountMenuItem);

        menuBar.add(accountMenu);

        frame.setJMenuBar(menuBar);
    }

    private void loadMainPanelLayoutConstraints() {

        mainPanelLayoutConstrains = new GridBagConstraints();

        mainPanelLayoutConstrains.gridx = 0;
        mainPanelLayoutConstrains.gridy = 0;
        mainPanelLayoutConstrains.fill = GridBagConstraints.BOTH;
        mainPanelLayoutConstrains.weightx = 1;
        mainPanelLayoutConstrains.weighty = 1;
    }

    private void changeMainPanelContent(ChangeableGui changeableGui) {

        mainPanel.removeAll();
        mainPanel.add(changeableGui.getMainPanel(), mainPanelLayoutConstrains);

        mainPanel.revalidate();
        mainPanel.repaint();
    }

    private void handleLogout() {

        frame.setJMenuBar(new JMenuBar());

        authService.logout();

        loginGui.handleLogout();
        changeMainPanelContent(loginGui);
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        mainPanel = new JPanel();
        mainPanel.setLayout(new GridBagLayout());
        mainPanel.setMinimumSize(new Dimension(0, 0));
        mainPanel.setPreferredSize(new Dimension(0, 0));
        mainPanel.setRequestFocusEnabled(true);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return mainPanel;
    }

}
