package org.example.gui.schema.add.fields.concrete;

import org.example.gui.schema.add.field.SchemaField;
import org.example.gui.schema.add.field.SchemaFieldGui;
import org.example.gui.schema.add.fields.SchemaFieldsGui;
import org.example.template.field.TemplateRowFieldType;

import javax.swing.*;
import java.util.List;
import java.util.function.Consumer;

public class SchemaCreatorGui extends ConcreteSchemaGui {

    private JPanel mainPanel;

    public SchemaCreatorGui(Consumer<SchemaFieldGui> onSelect) {

        super(onSelect);
    }

    @Override
    public JPanel getMainPanel() {

        return mainPanel;
    }

    private void createUIComponents() {
        // TODO: place custom component creation code here

        List<SchemaField> schemaFields = List.of(
                new SchemaField("name", "Nazwa firmy", TemplateRowFieldType.AREA),
                new SchemaField("street", "Ulica", TemplateRowFieldType.AREA),
                new SchemaField("post-code", "Kod pocztowy", TemplateRowFieldType.AREA),
                new SchemaField("city", "Miasto", TemplateRowFieldType.AREA),
                new SchemaField("nip", "Nip", TemplateRowFieldType.AREA)
        );

        schemaFieldsGui = new SchemaFieldsGui("Dane sprzedawcy", schemaFields, onSelect);

        mainPanel = schemaFieldsGui.getMainPanel();
    }

// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        createUIComponents();
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return mainPanel;
    }

}
