package org.example.gui.schema.add.fields.concrete;

import org.example.gui.schema.add.field.SchemaField;
import org.example.gui.schema.add.field.SchemaFieldGui;
import org.example.gui.schema.add.fields.SchemaFieldsGui;
import org.example.template.field.TemplateRowFieldType;
import org.example.template.row.TemplateRow;

import javax.swing.*;
import java.util.List;
import java.util.function.Consumer;

public class SchemaBasicInfoGui extends ConcreteSchemaGui<TemplateRow> {

    private JPanel mainPanel;

    public SchemaBasicInfoGui(Consumer<SchemaFieldGui> onSelect) {

        super(onSelect);
    }

    @Override
    public JPanel getMainPanel() {

        return mainPanel;
    }

    private void createUIComponents() {
        // TODO: place custom component creation code here

        List<SchemaField> schemaFields = List.of(
            new SchemaField("place", "Miejsce wystawienia", TemplateRowFieldType.AREA),
            new SchemaField("receiveDate", "Data zakończenia dostawy", TemplateRowFieldType.AREA),
            new SchemaField("creationDate", "Data wystawienia", TemplateRowFieldType.AREA),
            new SchemaField("title", "Numer faktury", TemplateRowFieldType.AREA)
        );

        schemaFieldsGui = new SchemaFieldsGui("Podstawowe informacje", schemaFields, onSelect);

        mainPanel = schemaFieldsGui.getMainPanel();
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        createUIComponents();
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return mainPanel;
    }
}
