package org.example.gui.schema.add.fields.concrete;

import org.example.gui.schema.add.field.SchemaField;
import org.example.gui.schema.add.field.SchemaFieldGui;
import org.example.gui.schema.add.fields.SchemaHeightFieldsGui;
import org.example.template.field.TemplateRowFieldType;

import javax.swing.*;
import java.util.Collections;
import java.util.List;
import java.util.function.Consumer;

public class SchemaProductsGui extends ConcreteSchemaGui {

    private JPanel mainPanel;

    public SchemaProductsGui(Consumer<SchemaFieldGui> onSelect) {

        super(onSelect);
    }

    @Override
    public JPanel getMainPanel() {

        return mainPanel;
    }

    private void createUIComponents() {
        // TODO: place custom component creation code here

        List<SchemaField> schemaFields = List.of(
//            new SchemaField("Wysokość", TemplateRowFieldType.HORIZONTAL),
            new SchemaField("index", "Numer (1,2,3 itp.)", TemplateRowFieldType.HORIZONTAL),
            new SchemaField("code", "Kod producenta", TemplateRowFieldType.HORIZONTAL),
            new SchemaField("name", "Nazwa", TemplateRowFieldType.HORIZONTAL),
            new SchemaField("price", "Cena netto", TemplateRowFieldType.HORIZONTAL),
            new SchemaField("quantity", "Ilość", TemplateRowFieldType.HORIZONTAL),
            new SchemaField("tax", "Podatek (%)", TemplateRowFieldType.HORIZONTAL)
        );

        schemaFieldsGui = new SchemaHeightFieldsGui("Dane o produktach", schemaFields, onSelect);

        mainPanel = schemaFieldsGui.getMainPanel();
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        createUIComponents();
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return mainPanel;
    }
}
