package org.example.gui.schema.add.fields.concrete;

import org.example.gui.schema.add.field.SchemaField;
import org.example.gui.schema.add.field.SchemaFieldGui;
import org.example.gui.schema.add.fields.SchemaHeightFieldsGui;
import org.example.template.field.TemplateRowFieldType;
import org.example.template.row.HeightTemplateRow;

import javax.swing.*;
import java.util.List;
import java.util.function.Consumer;

public class SchemaPayDateGui extends ConcreteSchemaGui<HeightTemplateRow> {

    private JPanel mainPanel;

    public SchemaPayDateGui(Consumer<SchemaFieldGui> onSelect) {

        super(onSelect);
    }

    @Override
    public JPanel getMainPanel() {

        return mainPanel;
    }

    private void createUIComponents() {
        // TODO: place custom component creation code here

        List<SchemaField> schemaFields = List.of(
            new SchemaField("value", "Data", TemplateRowFieldType.HORIZONTAL)
        );

        schemaFieldsGui = new SchemaHeightFieldsGui("Termin płatności", schemaFields, onSelect);

        mainPanel = schemaFieldsGui.getMainPanel();
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        createUIComponents();
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return mainPanel;
    }
}
