package org.example.gui.add_schema.fields.concrete;

import org.example.gui.ChangeableGui;
import org.example.gui.add_schema.fields.SchemaField;
import org.example.gui.add_schema.fields.SchemaFieldsGui;

import javax.swing.*;
import java.util.List;

public class SchemaCreatorGui extends ChangeableGui {

    private JPanel mainPanel;

    public SchemaCreatorGui() {

        $$$setupUI$$$();
    }

    @Override
    public JPanel getMainPanel() {

        return mainPanel;
    }

    private void createUIComponents() {
        // TODO: place custom component creation code here

        List<SchemaField> schemaFields = List.of(
            new SchemaField("Nazwa"),
            new SchemaField("Ulica"),
            new SchemaField("Kod pocztowy"),
            new SchemaField("Miasto"),
            new SchemaField("Nip")
        );

        SchemaFieldsGui schemaFieldsGui = new SchemaFieldsGui("Dane nadawcy", schemaFields);

        mainPanel = schemaFieldsGui.getMainPanel();
    }

// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        createUIComponents();
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return mainPanel;
    }

}
