package org.example.gui.add_schema.fields.concrete;

import org.example.gui.ChangeableGui;
import org.example.gui.add_schema.fields.SchemaField;
import org.example.gui.add_schema.fields.SchemaFieldType;
import org.example.gui.add_schema.fields.SchemaFieldsGui;

import javax.swing.*;
import java.util.List;

public class SchemaProductsGui extends ChangeableGui {

    private JPanel mainPanel;

    @Override
    public JPanel getMainPanel() {

        return mainPanel;
    }

    private void createUIComponents() {
        // TODO: place custom component creation code here

        List<SchemaField> schemaFields = List.of(
            new SchemaField("Wysokość", SchemaFieldType.ONLY_Y),
            new SchemaField("Indeks", SchemaFieldType.ONLY_X),
            new SchemaField("Symbol", SchemaFieldType.ONLY_X),
            new SchemaField("Nazwa", SchemaFieldType.ONLY_X),
            new SchemaField("Cena netto", SchemaFieldType.ONLY_X),
            new SchemaField("Ilość", SchemaFieldType.ONLY_X),
            new SchemaField("Podatek (%)", SchemaFieldType.ONLY_X)
        );

        SchemaFieldsGui schemaFieldsGui = new SchemaFieldsGui("Dane o produktach", schemaFields);

        mainPanel = schemaFieldsGui.getMainPanel();
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        createUIComponents();
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return mainPanel;
    }
}
