package org.example.gui.add_schema.fields.concrete;

import org.example.gui.add_schema.SchemaFieldsGuiAbstract;
import org.example.gui.add_schema.field.SchemaField;
import org.example.gui.add_schema.field.SchemaFieldGui;
import org.example.gui.add_schema.fields.SchemaHeightFieldsGui;
import org.example.template.field.TemplateRowFieldType;
import org.example.gui.add_schema.fields.SchemaFieldsGui;

import javax.swing.*;
import java.util.List;
import java.util.function.Consumer;

public class SchemaFinalPriceGui extends ConcreteSchemaGui {

    private JPanel mainPanel;

    public SchemaFinalPriceGui(Consumer<SchemaFieldGui> onSelect) {

        super(onSelect);
    }

    @Override
    public JPanel getMainPanel() {

        return mainPanel;
    }

    private void createUIComponents() {
        // TODO: place custom component creation code here

        List<SchemaField> schemaFields = List.of(
            new SchemaField("value", "Kwota", TemplateRowFieldType.HORIZONTAL)
        );

        schemaFieldsGui = new SchemaHeightFieldsGui("Cena końcowa", schemaFields, onSelect);

        mainPanel = schemaFieldsGui.getMainPanel();
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        createUIComponents();
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return mainPanel;
    }
}
