package org.example.gui.add_schema.fields;

import org.example.gui.ChangeableGui;
import org.example.template.field.TemplateRowFieldType;

import javax.swing.*;
import javax.swing.border.TitledBorder;
import javax.swing.plaf.FontUIResource;
import javax.swing.text.StyleContext;
import java.awt.*;
import java.util.Locale;

public class SchemaFieldGui extends ChangeableGui {

    private JPanel mainPanel;
    private JLabel titleLabel;
    private JLabel cordsLabel;
    private JButton selectPositionButton;
    private JCheckBox fieldIsHiddenCheckbox;
    private JTextField defaultValueInput;
    private JLabel cordsTitleLabel;
    private JCheckBox fieldRequiresSeparateCheckbox;
    private JTextField separatorInput;
    private JFormattedTextField separateIndexInput;

    public SchemaFieldGui(SchemaField schemaField) {

        $$$setupUI$$$();

        TemplateRowFieldType templateRowFieldType = schemaField.templateRowFieldType();

        String schemaFieldTypeName = templateRowFieldType.getName();
        String coords = templateRowFieldType.getCoords();

        titleLabel.setText(schemaField.title());
        cordsTitleLabel.setText(schemaFieldTypeName);
        cordsLabel.setText(coords);
    }

    @Override
    public JPanel getMainPanel() {

        return mainPanel;
    }

    private void createUIComponents() {
        // TODO: place custom component creation code here

    }

// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        mainPanel = new JPanel();
        mainPanel.setLayout(new GridBagLayout());
        mainPanel.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEmptyBorder(32, 0, 0, 0), null, TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, null, null));
        titleLabel = new JLabel();
        Font titleLabelFont = this.$$$getFont$$$(null, -1, 14, titleLabel.getFont());
        if (titleLabelFont != null) titleLabel.setFont(titleLabelFont);
        titleLabel.setText("Label");
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.gridwidth = 4;
        gbc.anchor = GridBagConstraints.WEST;
        mainPanel.add(titleLabel, gbc);
        fieldIsHiddenCheckbox = new JCheckBox();
        fieldIsHiddenCheckbox.setText("Pole jest ukryte");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.insets = new Insets(20, 0, 0, 0);
        mainPanel.add(fieldIsHiddenCheckbox, gbc);
        selectPositionButton = new JButton();
        selectPositionButton.setText("Wybór współrzędnych");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 2;
        gbc.insets = new Insets(20, 10, 0, 0);
        mainPanel.add(selectPositionButton, gbc);
        defaultValueInput = new JTextField();
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 1;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.insets = new Insets(20, 10, 0, 0);
        mainPanel.add(defaultValueInput, gbc);
        final JLabel label1 = new JLabel();
        label1.setText("Domyślna wartość");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 1;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.insets = new Insets(20, 20, 0, 0);
        mainPanel.add(label1, gbc);
        cordsLabel = new JLabel();
        Font cordsLabelFont = this.$$$getFont$$$(null, Font.PLAIN, -1, cordsLabel.getFont());
        if (cordsLabelFont != null) cordsLabel.setFont(cordsLabelFont);
        cordsLabel.setText("(0, 0), (0, 0)");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 2;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.insets = new Insets(20, 20, 0, 0);
        mainPanel.add(cordsLabel, gbc);
        cordsTitleLabel = new JLabel();
        cordsTitleLabel.setText("Label");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 2;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.insets = new Insets(20, 0, 0, 0);
        mainPanel.add(cordsTitleLabel, gbc);
        fieldRequiresSeparateCheckbox = new JCheckBox();
        fieldRequiresSeparateCheckbox.setText("Pole wymaga odzielenia");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 3;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.insets = new Insets(20, 0, 0, 0);
        mainPanel.add(fieldRequiresSeparateCheckbox, gbc);
        final JLabel label2 = new JLabel();
        label2.setText("Separator");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 3;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.insets = new Insets(20, 20, 0, 0);
        mainPanel.add(label2, gbc);
        separatorInput = new JTextField();
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 3;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.insets = new Insets(20, 10, 0, 0);
        mainPanel.add(separatorInput, gbc);
        final JLabel label3 = new JLabel();
        label3.setText("Pozycja");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 4;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.insets = new Insets(20, 20, 0, 0);
        mainPanel.add(label3, gbc);
        separateIndexInput = new JFormattedTextField();
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 4;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.insets = new Insets(20, 10, 0, 0);
        mainPanel.add(separateIndexInput, gbc);
    }

    /**
     * @noinspection ALL
     */
    private Font $$$getFont$$$(String fontName, int style, int size, Font currentFont) {
        if (currentFont == null) return null;
        String resultName;
        if (fontName == null) {
            resultName = currentFont.getName();
        } else {
            Font testFont = new Font(fontName, Font.PLAIN, 10);
            if (testFont.canDisplay('a') && testFont.canDisplay('1')) {
                resultName = fontName;
            } else {
                resultName = currentFont.getName();
            }
        }
        Font font = new Font(resultName, style >= 0 ? style : currentFont.getStyle(), size >= 0 ? size : currentFont.getSize());
        boolean isMac = System.getProperty("os.name", "").toLowerCase(Locale.ENGLISH).startsWith("mac");
        Font fontWithFallback = isMac ? new Font(font.getFamily(), font.getStyle(), font.getSize()) : new StyleContext().getFont(font.getFamily(), font.getStyle(), font.getSize());
        return fontWithFallback instanceof FontUIResource ? fontWithFallback : new FontUIResource(fontWithFallback);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return mainPanel;
    }

}
