package org.example.gui.add_schema;

import org.example.gui.ChangeableGui;;
import org.example.gui.Window;
import org.example.gui.integration.InvoicesGui;
import org.example.gui.pdf_viewer.PdfViewerGui;
import org.springframework.stereotype.Component;

import javax.swing.*;
import java.awt.*;

@Component
public class AddSchemaGui extends ChangeableGui {

    private JPanel mainPanel;
    private JPanel pdfViewerPanel;
    private JPanel managementPanel;

    private final PdfViewerGui pdfViewerGui;
    private final AddSchemaManagementGui addSchemaManagementGui;

    public AddSchemaGui(PdfViewerGui pdfViewerGui, AddSchemaManagementGui addSchemaManagementGui) {

        this.pdfViewerGui = pdfViewerGui;
        this.addSchemaManagementGui = addSchemaManagementGui;

        $$$setupUI$$$();
    }

    public void handleSelectPdf() {

        pdfViewerGui.handleSelectPdfFile();
    }

    @Override
    public JPanel getMainPanel() {

        return mainPanel;
    }

    private void createUIComponents() {
        // TODO: place custom component creation code here

        pdfViewerPanel = pdfViewerGui.getMainPanel();
        managementPanel = addSchemaManagementGui.getMainPanel();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        createUIComponents();
        mainPanel = new JPanel();
        mainPanel.setLayout(new GridBagLayout());
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.weightx = 8.0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.BOTH;
        mainPanel.add(pdfViewerPanel, gbc);
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.weightx = 3.0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.BOTH;
        mainPanel.add(managementPanel, gbc);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return mainPanel;
    }

}
