package org.example.gui.schema.view;

import org.example.gui.ChangeableGui;
import org.example.template.data.TemplateInvoiceItem;

import javax.swing.*;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import java.awt.*;
import java.util.List;

public class TemplateProductsViewGui extends ChangeableGui {

    private JPanel mainPanel;
    private DefaultTableModel productsTableModel;
    private JTable productsTable;

    public void updateProducts(List<TemplateInvoiceItem> products) {

        productsTableModel.setNumRows(0);

        if (products == null) {
            return;
        }

        for (int i = 0; i < products.size(); i++) {

            TemplateInvoiceItem product = products.get(i);

            Object[] productData = convertProductToRowValues(i + 1, product);

            productsTableModel.addRow(productData);
        }
    }

    private Object[] convertProductToRowValues(Integer index, TemplateInvoiceItem product) {

        return new Object[]{
                index,
                product.getCode(),
                product.getName(),
                product.getUnitPriceWithoutTax(false),
                product.getQuantity(),
                product.getTotalPriceWithoutTax(false),
                product.getTax()
        };
    }

    private void createUIComponents() {
        // TODO: place custom component creation code here

        DefaultTableCellRenderer cellsCenterRenderer = new DefaultTableCellRenderer();

        cellsCenterRenderer.setHorizontalAlignment(JLabel.CENTER);

        String[] headers = new String[]{"Indeks", "Kod", "Nazwa", "Cena netto", "Ilość", "Wartość netto", "Podatek (%)"};

        productsTableModel = new DefaultTableModel(headers, 0);
        productsTable = new JTable(productsTableModel);

        for (int i = 0; i < headers.length; i++) {

            TableColumn column = productsTable.getColumnModel().getColumn(i);

            column.setCellRenderer(cellsCenterRenderer);
        }
    }

    @Override
    public JPanel getMainPanel() {

        return mainPanel;
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        createUIComponents();
        mainPanel = new JPanel();
        mainPanel.setLayout(new GridBagLayout());
        final JScrollPane scrollPane1 = new JScrollPane();
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.BOTH;
        gbc.insets = new Insets(20, 0, 0, 0);
        mainPanel.add(scrollPane1, gbc);
        scrollPane1.setViewportView(productsTable);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return mainPanel;
    }

}
